import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import * as fs from 'fs';
import { getBlogContent, getBlogs } from '../../util';

type UnPromisify<T> = T extends Promise<infer U> ? U : T;
type Props = UnPromisify<ReturnType<typeof getStaticProps>>['props']
type Params = UnPromisify<ReturnType<typeof getStaticPaths>>['paths'][0]

export async function getStaticPaths() {
  const blogs = await getBlogs();

  return {
    paths: [
      ...blogs.map((name) => {
        return { params: { name } }
      }),
    ],
    fallback: false, // 没有匹配的 path，返回 404
  }
}

export async function getStaticProps({ params }: Params) {
  const [content] = await getBlogContent(params.name);

  return {
    props: {
      name: params.name,
      content,
    }
  }
}

export default function Blog(props: Props) {

  return (
    <div>
      <Head>
        <title>Blog - {props.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>{props.name}</h1>
        <p>{props.content}</p>
      </div>
    </div>
  );
}