import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import * as fs from 'fs';
import { AsyncFuncReturnType, getBlogs } from '../util';
import style from "../styles/index.module.css";

type Props = AsyncFuncReturnType<typeof getStaticProps>['props'];

export async function getStaticProps() {
  const blogs = await getBlogs();

  return {
    props: {
      blogs
    }
  };
}

export default function Home(props: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <div className={style.container}>
          <h1>Therainisme</h1>
          <p>There is nothing here.</p>
          <hr />
          {
            props.blogs.map((name: string) => {
              return (
                <Link key={name} href={`/blog/${name}`}>
                  <h3 className={style.blog}>
                    <a>{name}</a>
                    <time>2022年5月26日</time>
                  </h3>
                </Link>
              );
            })
          }
        </div>
      </main>

    </div>
  );
}
