import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import * as fs from 'fs';
import { getBlogs } from '../util';

// T extends U ? X : Y
// 如果 T 能赋值给 U，返回 X，否则返回 Y
type UnPromisify<T> = T extends Promise<infer U> ? U : T;
type Props = UnPromisify<ReturnType<typeof getStaticProps>>['props']

export async function getStaticProps() {
  const blogs = await getBlogs();

  return {
    props: {
      blogs
    }
  }
}

export default function Home(props: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        props.blogs.map((name: string) => {
          return (
            <Link key={name} href={`/blog/${name}`}>
              <div>
                <a key={name}>{name}</a>
              </div>
            </Link>
          );
        })
      }

    </div>
  )
}
